Creating new ap is
pagopa/pagopa-poc-quarkus pull request #4
Opened 2022-10-10 09:42 UTC by FedericoRuzzier

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-10-12 08:39 UTC, aomegax requested changes
please, remove `.DS_Store` from versioning.

this is an initial review :)

2022-10-12 08:39 UTC, aomegax commented on src/main/java/it/gov/pagopa/Controller/EnrollmentsController.java
> +import org.eclipse.microprofile.openapi.annotations.responses.APIResponses;
plaese, use [swagger-annotations](https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-annotations) lib instead of `org.eclipse`

2022-10-12 08:39 UTC, aomegax commented on src/main/java/it/gov/pagopa/Service/EnrollmentsService.java
> +        }catch(Exception e){
I don't prefer this approach, could you split the `catch` for the related exception classes?

2022-10-12 08:39 UTC, aomegax commented on src/main/java/it/gov/pagopa/Service/EnrollmentsService.java
> +            orgEnt.persistAndFlush();
why `flush`? is it necessary?

if you create organization entity, why you don't use it to create a dto (like a model) to return data to the caller?

2022-10-12 08:39 UTC, aomegax commented on src/main/java/it/gov/pagopa/Entity/OrganizationEntity.java
> +    private String organizationFiscalCode;
adopt a numeric id instead of a string to improve performances and then set unique on organizationFiscalCode to prevent duplicate

2022-10-12 08:39 UTC, aomegax commented on src/main/java/it/gov/pagopa/Entity/OrganizationEntity.java
> +    private String organizationOnboardingDate;
this field should be `LocalDateTime`

2022-10-12 08:39 UTC, aomegax commented on src/main/java/it/gov/pagopa/Entity/OrganizationEntity.java
> +    @Column(name = "organizationOnboardingDate")
don't specify `name` if it is the same of variable;

2022-10-27 14:04 UTC, FedericoRuzzier commented
Solved isssues, ready for approval

2022-10-28 16:01 UTC, aomegax approved these changes
👍 good!

2022-10-28 16:01 UTC, merged